[2025-02-07T21:40:12.421+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T21:40:12.427+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_four_python_files.run_gold scheduled__2025-02-07T12:39:00+00:00 [queued]>
[2025-02-07T21:40:12.430+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_four_python_files.run_gold scheduled__2025-02-07T12:39:00+00:00 [queued]>
[2025-02-07T21:40:12.430+0900] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-07T21:40:12.436+0900] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_gold> on 2025-02-07 12:39:00+00:00
[2025-02-07T21:40:12.443+0900] {logging_mixin.py:190} WARNING - /Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=29367) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-07T21:40:12.444+0900] {standard_task_runner.py:72} INFO - Started process 29372 to run task
[2025-02-07T21:40:12.443+0900] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'run_four_python_files', 'run_gold', 'scheduled__2025-02-07T12:39:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/run_four_files.py', '--cfg-path', '/var/folders/sp/pflbc_w93l76v3kjctmz_4tw0000gn/T/tmpk0nc3mjp']
[2025-02-07T21:40:12.445+0900] {standard_task_runner.py:105} INFO - Job 41: Subtask run_gold
[2025-02-07T21:40:12.466+0900] {task_command.py:467} INFO - Running <TaskInstance: run_four_python_files.run_gold scheduled__2025-02-07T12:39:00+00:00 [running]> on host macbook-pro-3.local
[2025-02-07T21:40:12.498+0900] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_four_python_files' AIRFLOW_CTX_TASK_ID='run_gold' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T12:39:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-07T12:39:00+00:00'
[2025-02-07T21:40:12.498+0900] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T21:40:12.507+0900] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/sp/pflbc_w93l76v3kjctmz_4tw0000gn/T
[2025-02-07T21:40:12.508+0900] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'python gold/combine_data.py']
[2025-02-07T21:40:12.512+0900] {subprocess.py:99} INFO - Output:
[2025-02-07T21:40:12.894+0900] {subprocess.py:106} INFO - 결합된 데이터가 'combined_data.csv'에 저장되었습니다.
[2025-02-07T21:40:12.926+0900] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-07T21:40:12.936+0900] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T21:40:12.936+0900] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=run_four_python_files, task_id=run_gold, run_id=scheduled__2025-02-07T12:39:00+00:00, execution_date=20250207T123900, start_date=20250207T124012, end_date=20250207T124012
[2025-02-07T21:40:12.950+0900] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T21:40:12.959+0900] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-07T21:40:12.960+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
