[2025-02-07T21:42:15.389+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T21:42:15.395+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_four_python_files.run_analysis scheduled__2025-02-07T12:41:00+00:00 [queued]>
[2025-02-07T21:42:15.398+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_four_python_files.run_analysis scheduled__2025-02-07T12:41:00+00:00 [queued]>
[2025-02-07T21:42:15.398+0900] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-07T21:42:15.405+0900] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_analysis> on 2025-02-07 12:41:00+00:00
[2025-02-07T21:42:15.412+0900] {logging_mixin.py:190} WARNING - /Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=29578) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-07T21:42:15.412+0900] {standard_task_runner.py:72} INFO - Started process 29580 to run task
[2025-02-07T21:42:15.411+0900] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'run_four_python_files', 'run_analysis', 'scheduled__2025-02-07T12:41:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/run_four_files.py', '--cfg-path', '/var/folders/sp/pflbc_w93l76v3kjctmz_4tw0000gn/T/tmpkzi2ltlg']
[2025-02-07T21:42:15.413+0900] {standard_task_runner.py:105} INFO - Job 50: Subtask run_analysis
[2025-02-07T21:42:15.435+0900] {task_command.py:467} INFO - Running <TaskInstance: run_four_python_files.run_analysis scheduled__2025-02-07T12:41:00+00:00 [running]> on host macbook-pro-3.local
[2025-02-07T21:42:15.468+0900] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_four_python_files' AIRFLOW_CTX_TASK_ID='run_analysis' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T12:41:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-07T12:41:00+00:00'
[2025-02-07T21:42:15.468+0900] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T21:42:15.477+0900] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/sp/pflbc_w93l76v3kjctmz_4tw0000gn/T
[2025-02-07T21:42:15.477+0900] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'python model/analysis/load_and_analysis3.py']
[2025-02-07T21:42:15.481+0900] {subprocess.py:99} INFO - Output:
[2025-02-07T21:42:17.199+0900] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-02-07T21:42:17.200+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/Desktop/bitcoin-data/model/analysis/load_and_analysis3.py", line 146, in <module>
[2025-02-07T21:42:17.200+0900] {subprocess.py:106} INFO -     model = DQN.load("/model/dqn_multitimeframe_trading_model.zip")
[2025-02-07T21:42:17.200+0900] {subprocess.py:106} INFO -             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-07T21:42:17.200+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/stable_baselines3/common/base_class.py", line 681, in load
[2025-02-07T21:42:17.200+0900] {subprocess.py:106} INFO -     data, params, pytorch_variables = load_from_zip_file(
[2025-02-07T21:42:17.201+0900] {subprocess.py:106} INFO -                                       ^^^^^^^^^^^^^^^^^^^
[2025-02-07T21:42:17.201+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/stable_baselines3/common/save_util.py", line 403, in load_from_zip_file
[2025-02-07T21:42:17.201+0900] {subprocess.py:106} INFO -     file = open_path(load_path, "r", verbose=verbose, suffix="zip")
[2025-02-07T21:42:17.201+0900] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-07T21:42:17.201+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/functools.py", line 909, in wrapper
[2025-02-07T21:42:17.202+0900] {subprocess.py:106} INFO -     return dispatch(args[0].__class__)(*args, **kw)
[2025-02-07T21:42:17.202+0900] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-07T21:42:17.202+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/stable_baselines3/common/save_util.py", line 240, in open_path_str
[2025-02-07T21:42:17.202+0900] {subprocess.py:106} INFO -     return open_path_pathlib(pathlib.Path(path), mode, verbose, suffix)
[2025-02-07T21:42:17.202+0900] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-07T21:42:17.203+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/stable_baselines3/common/save_util.py", line 291, in open_path_pathlib
[2025-02-07T21:42:17.203+0900] {subprocess.py:106} INFO -     return open_path_pathlib(path, mode, verbose, suffix)
[2025-02-07T21:42:17.203+0900] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-07T21:42:17.203+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/stable_baselines3/common/save_util.py", line 272, in open_path_pathlib
[2025-02-07T21:42:17.203+0900] {subprocess.py:106} INFO -     raise error
[2025-02-07T21:42:17.203+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/stable_baselines3/common/save_util.py", line 264, in open_path_pathlib
[2025-02-07T21:42:17.204+0900] {subprocess.py:106} INFO -     return open_path(path.open("rb"), mode, verbose, suffix)
[2025-02-07T21:42:17.204+0900] {subprocess.py:106} INFO -                      ^^^^^^^^^^^^^^^
[2025-02-07T21:42:17.204+0900] {subprocess.py:106} INFO -   File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/pathlib.py", line 1013, in open
[2025-02-07T21:42:17.204+0900] {subprocess.py:106} INFO -     return io.open(self, mode, buffering, encoding, errors, newline)
[2025-02-07T21:42:17.204+0900] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-02-07T21:42:17.204+0900] {subprocess.py:106} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/model/dqn_multitimeframe_trading_model.zip.zip'
[2025-02-07T21:42:17.505+0900] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-07T21:42:17.510+0900] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-07T21:42:17.514+0900] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=run_four_python_files, task_id=run_analysis, run_id=scheduled__2025-02-07T12:41:00+00:00, execution_date=20250207T124100, start_date=20250207T124215, end_date=20250207T124217
[2025-02-07T21:42:17.519+0900] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T21:42:17.520+0900] {standard_task_runner.py:124} ERROR - Failed to execute job 50 for task run_analysis (Bash command failed. The command returned a non-zero exit code 1.; 29580)
Traceback (most recent call last):
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-07T21:42:17.555+0900] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-07T21:42:17.562+0900] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-07T21:42:17.563+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
