[2025-02-07T21:41:11.234+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-07T21:41:11.239+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_four_python_files.run_gold scheduled__2025-02-07T12:40:00+00:00 [queued]>
[2025-02-07T21:41:11.242+0900] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_four_python_files.run_gold scheduled__2025-02-07T12:40:00+00:00 [queued]>
[2025-02-07T21:41:11.242+0900] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-07T21:41:11.248+0900] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_gold> on 2025-02-07 12:40:00+00:00
[2025-02-07T21:41:11.255+0900] {logging_mixin.py:190} WARNING - /Users/jingyounglee/miniforge3/envs/bitcoin/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=29463) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-07T21:41:11.255+0900] {standard_task_runner.py:72} INFO - Started process 29467 to run task
[2025-02-07T21:41:11.254+0900] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'run_four_python_files', 'run_gold', 'scheduled__2025-02-07T12:40:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/run_four_files.py', '--cfg-path', '/var/folders/sp/pflbc_w93l76v3kjctmz_4tw0000gn/T/tmp5ijzjbol']
[2025-02-07T21:41:11.256+0900] {standard_task_runner.py:105} INFO - Job 45: Subtask run_gold
[2025-02-07T21:41:11.276+0900] {task_command.py:467} INFO - Running <TaskInstance: run_four_python_files.run_gold scheduled__2025-02-07T12:40:00+00:00 [running]> on host macbook-pro-3.local
[2025-02-07T21:41:11.306+0900] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='run_four_python_files' AIRFLOW_CTX_TASK_ID='run_gold' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T12:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-07T12:40:00+00:00'
[2025-02-07T21:41:11.307+0900] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-07T21:41:11.315+0900] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/sp/pflbc_w93l76v3kjctmz_4tw0000gn/T
[2025-02-07T21:41:11.315+0900] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'python gold/combine_data.py']
[2025-02-07T21:41:11.319+0900] {subprocess.py:99} INFO - Output:
[2025-02-07T21:41:11.666+0900] {subprocess.py:106} INFO - 결합된 데이터가 'combined_data.csv'에 저장되었습니다.
[2025-02-07T21:41:11.696+0900] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-07T21:41:11.705+0900] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-07T21:41:11.706+0900] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=run_four_python_files, task_id=run_gold, run_id=scheduled__2025-02-07T12:40:00+00:00, execution_date=20250207T124000, start_date=20250207T124111, end_date=20250207T124111
[2025-02-07T21:41:11.721+0900] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-07T21:41:11.728+0900] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-07T21:41:11.729+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
